src/Entity/Death.php
<?php

namespace App\Entity;

use App\Repository\DeathRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DeathRepository::class)]
class Death
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $birthyear = null;

    #[ORM\Column(nullable: true)]
    private ?int $age = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Country $birthcountry = null;

    #[ORM\ManyToOne(inversedBy: 'deaths')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Country $deathcountry = null;

    #[ORM\ManyToOne(inversedBy: 'deaths')]
    #[ORM\JoinColumn(nullable: true)]
    private ?DeathCause $deathcause = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 12, nullable: true)]
    private ?string $sex = null;

    #[ORM\Column]
    private ?int $death_year = null;

    #[ORM\ManyToOne(inversedBy: 'deaths')]
    private ?Department $death_department = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBirthyear(): ?int
    {
        return $this->birthyear;
    }

    public function setBirthyear(int $birthyear): static
    {
        $this->birthyear = $birthyear;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(?int $age): static
    {
        $this->age = $age;

        return $this;
    }

    public function getBirthcountry(): ?Country
    {
        return $this->birthcountry;
    }

    public function setBirthcountry(?Country $birthcountry): static
    {
        $this->birthcountry = $birthcountry;

        return $this;
    }

    public function getDeathcountry(): ?Country
    {
        return $this->deathcountry;
    }

    public function setDeathcountry(?Country $deathcountry): static
    {
        $this->deathcountry = $deathcountry;

        return $this;
    }

    public function getDeathcause(): ?DeathCause
    {
        return $this->deathcause;
    }

    public function setDeathcause(?DeathCause $deathcause): static
    {
        $this->deathcause = $deathcause;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(?string $sex): static
    {
        $this->sex = $sex;

        return $this;
    }

    public function getDeathYear(): ?int
    {
        return $this->death_year;
    }

    public function setDeathYear(int $death_year): static
    {
        $this->death_year = $death_year;

        return $this;
    }

    public function getDeathDepartment(): ?Department
    {
        return $this->death_department;
    }

    public function setDeathDepartment(?Department $death_department): static
    {
        $this->death_department = $death_department;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\DeathCauseRepository;
use App\Repository\DeathRepository;
use App\Service\DataGenerator;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class HomeController extends AbstractController
{
    private DataGenerator $dataGenerator;

    public function __construct(DataGenerator $dataGenerator)
    {
        $this->dataGenerator = $dataGenerator;
    }

    #[Route('/', name: 'app_home')]
    public function index(DeathRepository $deathRepository, DeathCauseRepository $deathCauseRepository): Response
    {
        try {
            if ($deathRepository->count() === 0) {
                $this->dataGenerator->importDataFromCSV();
            }
        } catch (\Exception $e) {
            echo "data not found. Error : " . $e;
        }

        $d = array(
            "électrocuté.e",
            "écrasé.e",
            "d'un coup de foudre",
            "d'une attaque d'extraterrestre",
            "d'une attaque de dinosaures",
            "noyé.e",
            "d'hésitation",
            "parce qu'un météore vous est tombé dessus",
            "de rire",
            "d'une coupure de papier, ouch",
            "juste après avoir trouvé un ticket de loto gagnant, mince",
            "assomé.e par une enclume",
            "d'une overdose de café",
            "empoisonné.e par votre animal de compagnie",
            "d'embarras",
            "parce que l'Apocalpse vient d'arriver"
        );

        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'deathsStats' => $deathRepository,
            'deathsCauses' => $deathCauseRepository,
            'listeMorts' => $d,

        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ryuk - Home
{% endblock %}

{% block content %}
	<h2>Une mort est si vite arrivée...</h2>

	<br>
	<div>
		Aujourd'hui, vous pourriez mourir
		<span class="fw-bold">{{ random(listeMorts) }}</span>.
	</div>

	<br>
	<div>
		Nombre de morts dans le monde depuis le chargement de cette page :
		<table class="table table-bordered text-center top-0 start-50" style="width: 6rem;">
			<tbody>
				<tr id="compteur">
					{% for i in 11..0 %}
						{% if (i%6 < 3) %}
							<td class="table-dark table-active" id="compteur-num{{ i }}">0</td>
						{% else %}
							<td class="table-dark" id="compteur-num{{ i }}">0</td>
						{% endif %}
					{% endfor %}
				</tr>
			</tbody>
		</table>
	</div>

	<br>
	<article>
		<div class="card">
			<h2>
				Top 5 des causes de décès
			</h2>
			<table class="table table-dark table-striped table-bordered table-hover rounded-3">
				<thead>
					<tr>
						<th>Maladie</th>
						<th>Compte</th>
					</tr>
				</thead>
				<tbody>
					{% for deathCause in deathsCauses.findTop5DeathCause %}
						<tr>
							<td>{{ deathCause.title }}</td>
							<td>{{ deathCause.deathCount }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

		<div class="card">
			<h2>
				Top 5 des prénoms les plus mortels
			</h2>
			<table class="table table-dark table-striped table-bordered table-hover rounded-3">
				<thead>
					<tr>
						<th>Prénoms</th>
						<th>Compte</th>
					</tr>
				</thead>
				<tbody>
					{% for death in deathsStats.findTop5FirstName %}
						<tr>
							<td>{{ death.firstName }}</td>
							<td>{{ death.deathCount }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

		<div class="card">
			<h2>
				Top 5 des départements dangereux
			</h2>
			<table class="table table-dark table-striped table-bordered table-hover rounded-3">
				<thead>
					<tr>
						<th>Département</th>
						<th>Compte</th>
					</tr>
				</thead>
				<tbody>
					{% for death in deathsStats.findTop5Departments %}
						<tr>
							<td>{{ death.departmentName }}</td>
							<td>{{ death.deathCount }}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>

		<script src={{ asset('js/compteur.js') }}></script>
	</article>
{% endblock %}